name: Build debian image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      maintainer:
        description: 'Maintainer'
        default: "Open Source <opensource@peraMIC.io>"
        required: true
      support:
        description: 'Support'
        default: "support@peraMIC.io"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - run: docker run --workdir /github/workspace --rm --privileged -e ARCH -e DIST -e APT -e MIRROR -e VERSION -e MAINTAINER -e SUPPORT --entrypoint bash -v "$GITHUB_WORKSPACE":"/github/workspace" debian:stretch-slim "-c" "./mkimg"
        env:
          ARCH: 'armhf'
          DIST: 'stretch'
          APT: 'https://peramic.github.io/debian'
          MIRROR: 'http://httpredir.debian.org/debian'
          VERSION: ${{ github.event.inputs.version }}
          MAINTAINER: ${{ github.event.inputs.maintainer }}
          SUPPORT: ${{ github.event.inputs.support }}
        id: build
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.IMAGE }}
          asset_name: ${{ steps.build.outputs.IMAGE }}
          asset_content_type: application/zip
